In [1]:
# Creating a numpy array

import numpy as np
my_list = [1,2,3,4,5]
np_list = np.array(my_list)
print(np_list)
print(type(np_list))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
# Perform arithmatic on a numpy array
np_list_m = 0.5 * np_list
print(np_list_m)

[0.5 1.  1.5 2.  2.5]


In [4]:
# Subsetting numpy array
low = np_list < 3
high = np_list > 3
print(np_list[low])
print(np_list[high])

[1 2]
[4 5]


In [5]:
# Creating a 2D numpy array

arr_2d = np.array([[1,2,3], [4,5,6]])

print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [7]:
# Shape of an array

print(arr_2d.shape)

(2, 3)


In [8]:
# Subsetting 2d Array

print(arr_2d[0][2]) #Prints 3
print(arr_2d[:, 0:2])

3
[[1 2]
 [4 5]]
